# Generated by Django 4.2.21 on 2025-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.AddField(
            model_name='espacio',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
